### ISSUE TITLE
Malicious Indicators

### ISSUE THREAD

**Issue by JohannesTK** [mfkp/tinderplusplus#27]
Hey there!

Just ran the application through hybrid-analysis and it shows some concerns - https://www.hybrid-analysis.com/sample/39787bc11283349e33ad17b4add7f1d4cdd198b660632af70882ddb89131b454?environmentId=1 

Not saying that anything is wrong but wondering why the application needs to shutdown/reboot the machine, interact with a device drivers, queries process information and etc?

**Comment by mfkp** [comment]
Well, the app itself doesn't use any of that, but it's built on top of https://github.com/nwjs/nw.js, which builds packaged desktop apps which contain a full Chromium runtime environment. I imagine Chrome/Chromium would have the capabilities listed above, and that's why it would show up in the analysis.

**Comment by JohannesTK** [comment]
Alright. Thanks for the clarifications. 

By the way, great job on the application!
